name: context_engine
channels:
  - snowflake
dependencies:
  - python=3.10
  - streamlit
  - snowflake-snowpark-python
  - snowflake-ml-python
  - pyyaml
  - pip:
      - python-pptx
      - python-docx
      - PyPDF2
