"""
Custom Instructions Generator
===============================
Compiles business rules, caveats, and access patterns into Cortex Analyst
custom instructions — plain text directives that guide SQL generation.
"""

from lib.snowflake_connection import call_cortex_complete
from lib.context_store import get_all_facts


def generate_custom_instructions(session_id: str) -> str:
    """Generate Cortex Analyst custom instructions from captured context.

    Returns formatted plain text instructions.
    """
    facts = get_all_facts(session_id)
    if not facts:
        return "# No context captured yet."

    # Collect relevant facts by category
    rules = [f["FACT_TEXT"] for f in facts if f.get("CATEGORY") == "business_rule"]
    caveats = [f["FACT_TEXT"] for f in facts if f.get("CATEGORY") == "caveat"]
    access = [f["FACT_TEXT"] for f in facts if f.get("CATEGORY") == "access_pattern"]
    terms = [f["FACT_TEXT"] for f in facts if f.get("CATEGORY") == "terminology"]

    if not any([rules, caveats, access, terms]):
        return "# No business rules, caveats, or access patterns captured yet."

    # Use LLM to clean up and consolidate into clear instructions
    raw_instructions = []

    if rules:
        raw_instructions.append("BUSINESS RULES:")
        raw_instructions.extend(f"- {r}" for r in rules)
    if caveats:
        raw_instructions.append("\nDATA CAVEATS:")
        raw_instructions.extend(f"- {c}" for c in caveats)
    if access:
        raw_instructions.append("\nACCESS RESTRICTIONS:")
        raw_instructions.extend(f"- {a}" for a in access)
    if terms:
        raw_instructions.append("\nBUSINESS TERMINOLOGY:")
        raw_instructions.extend(f"- {t}" for t in terms[:20])

    raw_text = "\n".join(raw_instructions)

    prompt = f"""You are helping create custom instructions for a Snowflake Cortex Analyst AI agent.
These instructions will guide how the agent generates SQL queries.

Here are the raw business rules, caveats, access restrictions, and terminology collected from interviews:

{raw_text}

Rewrite these into a clean, well-organized set of instructions for the AI agent. The instructions should:
1. Be clear and actionable — each instruction should tell the agent what to DO or NOT DO
2. Be organized by topic (data rules, terminology, restrictions)
3. Remove duplicates and consolidate related instructions
4. Use imperative language (e.g., "Always filter...", "Never expose...", "Use X when calculating Y")
5. Keep it concise — the total should be under 2000 words

Format as a numbered list grouped by section headers. Do NOT wrap in markdown code blocks."""

    try:
        instructions = call_cortex_complete(prompt)
        return instructions.strip()
    except Exception:
        # Fall back to raw instructions
        return raw_text


def generate_markdown_doc(session_id: str) -> str:
    """Generate a comprehensive human-readable Markdown document of all context.

    This is the human-editable version of everything captured.
    """
    facts = get_all_facts(session_id)
    if not facts:
        return "# Context Document\n\nNo context captured yet."

    # Group facts by category
    by_category = {}
    for f in facts:
        cat = f.get("CATEGORY", "other")
        if cat not in by_category:
            by_category[cat] = []
        by_category[cat].append(f)

    # Build document
    doc_parts = ["# Data Context Document\n"]
    doc_parts.append("*Generated by Snowflake Context Engine*\n")
    doc_parts.append("---\n")

    # Table descriptions
    if "table_description" in by_category:
        doc_parts.append("## Databases, Schemas & Tables\n")
        # Group by entity
        by_table = {}
        for f in by_category["table_description"]:
            key = f.get("ENTITY_TABLE", "General")
            if f.get("ENTITY_SCHEMA"):
                key = f"{f['ENTITY_SCHEMA']}.{key}"
            if f.get("ENTITY_DATABASE"):
                key = f"{f['ENTITY_DATABASE']}.{key}"
            if key not in by_table:
                by_table[key] = []
            by_table[key].append(f["FACT_TEXT"])

        for table_name, descs in sorted(by_table.items()):
            doc_parts.append(f"### `{table_name}`\n")
            for desc in descs:
                doc_parts.append(f"- {desc}\n")
            doc_parts.append("")

    # Relationships
    if "relationship" in by_category:
        doc_parts.append("## Table Relationships\n")
        for f in by_category["relationship"]:
            doc_parts.append(f"- {f['FACT_TEXT']}\n")
        doc_parts.append("")

    # Business terminology
    if "terminology" in by_category:
        doc_parts.append("## Business Terminology\n")
        doc_parts.append("| Term | Definition |")
        doc_parts.append("|------|-----------|")
        for f in by_category["terminology"]:
            text = f["FACT_TEXT"]
            # Try to split into term/definition
            if " means " in text.lower():
                parts = text.split(" means ", 1)
                doc_parts.append(f"| {parts[0].strip()} | {parts[1].strip()} |")
            elif " - " in text:
                parts = text.split(" - ", 1)
                doc_parts.append(f"| {parts[0].strip()} | {parts[1].strip()} |")
            else:
                doc_parts.append(f"| — | {text} |")
        doc_parts.append("")

    # Metrics & KPIs
    if "metric_definition" in by_category:
        doc_parts.append("## Metrics & KPIs\n")
        doc_parts.append("| Metric | Definition | Source Table |")
        doc_parts.append("|--------|-----------|-------------|")
        for f in by_category["metric_definition"]:
            table = f.get("ENTITY_TABLE", "—")
            doc_parts.append(f"| {f.get('ENTITY_COLUMN', '—')} | {f['FACT_TEXT']} | `{table}` |")
        doc_parts.append("")

    # Business Rules
    if "business_rule" in by_category:
        doc_parts.append("## Business Rules\n")
        for i, f in enumerate(by_category["business_rule"], 1):
            doc_parts.append(f"{i}. {f['FACT_TEXT']}\n")
        doc_parts.append("")

    # Caveats
    if "caveat" in by_category:
        doc_parts.append("## Data Caveats & Gotchas\n")
        for f in by_category["caveat"]:
            doc_parts.append(f"- ⚠️ {f['FACT_TEXT']}\n")
        doc_parts.append("")

    # Access Patterns
    if "access_pattern" in by_category:
        doc_parts.append("## Access Patterns & Security\n")
        for f in by_category["access_pattern"]:
            doc_parts.append(f"- 🔒 {f['FACT_TEXT']}\n")
        doc_parts.append("")

    return "\n".join(doc_parts)
